version: '3.8'
services:
  auth-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - '3001:3000'
    volumes:
      - ./apps/backend/services/auth-service:/app/apps/backend/services/auth-service
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - '3000:3000'
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - /app/node_modules
    environment:
      - NODE_ENV=development
