version: '3.8'

services:
  auth-service:
    build:
      context: . # Контекст сборки — корень проекта
      dockerfile: docker/Dockerfile.auth # Путь к Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - ./apps/backend/services/auth-service:/app/apps/backend/services/auth-service
    environment:
      - NODE_ENV=development
    command: pnpm start:dev

  frontend:
    build:
      context: . # Контекст сборки — корень проекта
      dockerfile: docker/Dockerfile.frontend # Путь к Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./apps/frontend:/app/apps/frontend
    environment:
      - NODE_ENV=development
    command: pnpm dev
