FROM node:18
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/frontend ./apps/frontend/
RUN npm install -g pnpm && pnpm install --frozen-lockfile
# Указываем конкретную версию next и очищаем кэш
RUN pnpm cache clean && pnpm add next@15.2.2 -w
CMD ["npx", "--yes", "next", "dev", "--turbopack", "apps/frontend"]