version: '3.8'
services:
  auth-service:
    build:
      context: ./apps/backend/services/auth-service
      dockerfile: Dockerfile
    ports:
      - '3001:3000' # Изменим порт, чтобы не конфликтовал с фронтендом
    volumes:
      - ./apps/backend/services/auth-service:/app
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./apps/frontend:/app
